spring:
  application:
    name: api-gateway
  cloud:
    config:
      profile: dev
  config:
    import: optional:configserver:http://localhost:8888
#
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    prefer-ip-address: true
server:
  port: 9010